before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
    # override $NODE_VERSION
    - CI_COMMIT_MESSAGE="$(git log -1 --pretty=%s)" && if (printf "$CI_COMMIT_MESSAGE" | grep -qE "\bNODE_VERSION="); then nvm install "$(printf "$CI_COMMIT_MESSAGE" | sed -e "s/.*\bNODE_VERSION=//" -e "s/ .*//")" && node --version && npm --version; fi
branches:
    only:
    - /^alpha$/
    - /^beta$/
    - /^benchmark\..*/
    - /^cron$/
    - /^docker\..*/
    - /^master$/
    - /^publish$/
    - /^task$/
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: pfBACw2JxS9iWFQCuO+iE/EL7UTuMAiE3VGJRaHH/+R77rfdBmIyg3mXdizxl3wWA9wyYcnZhq3RqDrhJyL7oqlPV3piWuuRAXpwN2hsRN5QR0kq5z4Q1Y5mwJ+nZjeyLHY43w04fEt0wkDLIeg8TGFdZabMOSlm5XMnbQQRpcen613eC5JW5MwqTvf/Yn6gOmD9ZP0rCJftgKmJif0VZN2emBxJht9N53OJGqD0gQs0VwObISV7Xk8viTPE/KWG9P2YSBvMDbCJ1T9LifBD5cOm1rRYbc3RcP4lwiX2J1UHsdUH/AbG6eFNFSxi0bn/VF47DCvAs0EUjTsZMGzfdxLwJKo+vlU0qLvqOJZzs6WozTxKzj9G0ebdqZxEniicqrDQIwABaSAf6x/NcPp094hjj5DHPdA3ZxOBcuxwTjM5x6QIF304Tj/cPo6pJPKuB9AWj/+6zckfGd137/3EbO8LHTHL7PxONYVIOeQcUpPRh+zJuQowPKRaAp0/NbCdBxMG13KuYOyxCmdmfLhaH4lXhamM3LXmXQydcpK6MFUtGSliuF4u4y93DEtyKRzQTfMgi1tz/YbPgRsVFjT7adB8O+bj4CXgA/l2gogLwGYNYN9Sw09/3ZxZh+zqbdx7pdf4XTWFf+gbZ5J33feUiEogAW0KpZU07o9Tt9RYWyo= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    # - 8
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
